project:
  type: website

website:
  title: "Felipe's Lab Notes"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - about.qmd

format:
  html:
    theme:
    - darkly
    - theme.scss
    toc: true



